server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.zhifa.jwtdemo.entity
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://47.100.45.101:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhifa123

